# Generated by Django 3.0 on 2022-06-13 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LabAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='duration',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='normal_range',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='speciment_det',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_logins',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LabAdmin.UserRoles'),
        ),
        migrations.AlterField(
            model_name='user_logins',
            name='user_status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
