# Generated by Django 3.0 on 2022-06-12 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LabAdmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Trans')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=5)),
                ('is_child', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=255)),
                ('doc_name', models.CharField(max_length=100)),
                ('hosp_name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('discount_total', models.FloatField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('archived', models.CharField(blank=True, max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CustomerBilling.Customer')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LabAdmin.Doctors')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LabAdmin.Hospital')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='originalBillTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billsample', models.FileField(upload_to='billing')),
            ],
        ),
        migrations.CreateModel(
            name='originalResultTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testsample', models.FileField(upload_to='testresult')),
            ],
        ),
        migrations.CreateModel(
            name='UserBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billdetails', models.FileField(upload_to='customerBill')),
                ('resultdetails', models.FileField(blank=True, null=True, upload_to='customerResult')),
                ('billid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomerBilling.CustomerBilling')),
            ],
        ),
        migrations.CreateModel(
            name='fin_transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(blank=True, max_length=25, null=True)),
                ('comments', models.CharField(blank=True, max_length=350, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomerBilling.CustomerBilling')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillingTestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', jsonfield.fields.JSONField(blank=True, null=True)),
                ('discount', jsonfield.fields.JSONField(blank=True, null=True)),
                ('billid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomerBilling.CustomerBilling')),
            ],
        ),
    ]
