# Generated by Django 3.0 on 2022-06-13 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LabAdmin', '0002_auto_20220613_2155'),
        ('CustomerBilling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbilling',
            name='doc_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerbilling',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LabAdmin.Doctors'),
        ),
        migrations.AlterField(
            model_name='customerbilling',
            name='hosp_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerbilling',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LabAdmin.Hospital'),
        ),
        migrations.AlterField(
            model_name='customerbilling',
            name='is_child',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
